(() => {
  'use strict';
  const $ = (selector, root=document) => root.querySelector(selector);
  const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
  const KEY='devlingo_user', tracks=window.DEVLINGO_TRACKS;
  const START={entry:1,pro:tracks[0].lessons.length+1,expert:tracks[0].lessons.length+tracks[1].lessons.length+1};
  const BADGES={html:['Markup Scout','You can read and build page structure, semantics, media, and accessible controls.'],css:['Style Starter','You can inspect selectors, the cascade, spacing, layout, responsive behavior, and focus states.'],js:['Script Builder','You can connect page behavior to JavaScript and reason about state.'],jquery:['jQuery Sprinter','You can select, update, and animate page elements with jQuery.']};
  const label=window.DEVLINGO_TRACKS.flatMap(t=>t.lessons.map((l,i)=>({id:`${t.id}-${i+1}`,track:t.id,lesson:i+1,title:l.title})));
  let user=null, selectedTier='entry', activeTrack='html', activeNode=null, toastTimer=null, previewTimer=null, audio;
  const today=()=>new Date().toLocaleDateString('en-CA');
  function persist(){localStorage.setItem(KEY,JSON.stringify(user));}
  function sound(ok=true){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.setValueAtTime(ok?660:190,audio.currentTime);if(ok)o.frequency.exponentialRampToValueAtTime(990,audio.currentTime+.16);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.12,audio.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+(ok?.32:.18));o.start();o.stop(audio.currentTime+(ok?.33:.19));}catch(_){}}
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400);}
  function updateStreak(){const now=today();if(user.lastActive!==now){const yesterday=new Date(Date.now()-86400000).toLocaleDateString('en-CA');user.streak=user.lastActive===yesterday?(user.streak||0)+1:1;user.lastActive=now;persist();}}
  function init(){try{user=JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){user=null}if(!user){$('#onboarding').hidden=false;return}user.completedNodes=user.completedNodes||[];user.badges=user.badges||[];user.hearts=Number.isFinite(user.hearts)?user.hearts:5;user.streak=user.streak||1;user.xp=user.xp||0;user.level=user.level||1;user.startTier=user.startTier||'entry';if(!user.curriculumVersion){const oldStarts={entry:1,pro:6,expert:12},offset=Math.max(0,user.level-(oldStarts[user.startTier]||1));user.startLevel=START[user.startTier]||1;user.level=user.startLevel+offset;user.curriculumVersion=2;persist()}user.startLevel=user.startLevel||START[user.startTier]||1;const initialTrack=tracks.find(t=>{const start=user.startLevel-1,base=tracks.slice(0,tracks.indexOf(t)).reduce((n,x)=>n+x.lessons.length,0);return start>=base&&start<base+t.lessons.length});if(initialTrack)activeTrack=initialTrack.id;updateStreak();applyTheme();render();}
  function applyTheme(){const dark=user&&user.theme==='dark';document.body.classList.toggle('dark',!!dark);$('#themeLabel').textContent=dark?'Light mode':'Dark mode';}
  function unlockedIndex(){return Math.max((user.level||1)-1,(user.startLevel||1)-1);}
  function render(){if(!user)return;$('#heartsCount').textContent=user.hearts;$('#streakCount').textContent=user.streak;$('#xpCount').textContent=user.xp;$('#profileButton').textContent=(user.name||'?').trim().charAt(0).toUpperCase();$('#welcomeTitle').textContent=`${user.name?`Hey, ${user.name}.`:'Keep your momentum going.'}`;$('#welcomeSub').textContent=user.name?'Ready for another little win?':'A few minutes of practice can change everything.';
    $('#trackNav').innerHTML=tracks.map(t=>`<button class="track-link ${t.id===activeTrack?'active':''}" data-track="${t.id}"><span class="track-icon">${t.icon}</span><span><span class="track-name">${t.name}</span><span class="track-mini">${t.lessons.filter((_,i)=>user.completedNodes.includes(`${t.id}-${i+1}`)).length}/${t.lessons.length} LESSONS</span></span></button>`).join('');
    $('#badgesStrip').innerHTML=user.badges.length?user.badges.map(id=>`<span class="earned-badge" title="${BADGES[id]?.[1]||''}">🏅 ${BADGES[id]?.[0]||id}</span>`).join(''):'<span class="badge-prompt">Complete every lesson in a track to earn a badge and recognition.</span>';
    const t=tracks.find(x=>x.id===activeTrack)||tracks[0];$('#trackTitle').textContent=t.name;$('#trackEyebrow').textContent=`${t.short.toUpperCase()} · YOUR SKILL PATH`;const completed=t.lessons.filter((_,i)=>user.completedNodes.includes(`${t.id}-${i+1}`)).length;$('#progressText').textContent=`${completed} of ${t.lessons.length} completed`;$('#progressPercent').textContent=`${Math.round(completed/t.lessons.length*100)}%`;$('#trackProgress').style.width=`${completed/t.lessons.length*100}%`;
    const offset=tracks.slice(0,tracks.indexOf(t)).reduce((n,x)=>n+x.lessons.length,0),currentIndex=(user.level||1)-1;$('#pathMap').innerHTML=t.lessons.map((l,i)=>{const id=`${t.id}-${i+1}`,done=user.completedNodes.includes(id),global=offset+i,openStudy=t.id==='html'||t.id==='css',allowed=done||openStudy||global<=unlockedIndex(),current=!done&&global===currentIndex;return `<div class="node-row"><button class="lesson-node ${done?'done':current?'active':''} ${done?'review':''}" data-node="${id}" ${allowed?'':'disabled'} aria-label="${done?'Review':current?'Start':allowed?'Available':'Locked'} lesson: ${l.title}">${done?'✓':allowed?'<span>✦</span>':'🔒'}${current?'<span class="node-bubble">START HERE →</span>':''}<span class="node-label">${l.title}</span></button></div>`}).join('');}
  function startUser(){const tier=selectedTier,name=$('#studentName').value.trim();user={name,level:START[tier],startLevel:START[tier],xp:0,streak:1,hearts:5,completedNodes:[],badges:[],lastActive:today(),theme:'light',startTier:tier,curriculumVersion:2};let n=START[tier]-1;for(const t of tracks){if(n<t.lessons.length){activeTrack=t.id;break}n-=t.lessons.length;}persist();$('#onboarding').hidden=true;render();toast(`You're in, ${name||'friend'}! Let's make something.`);}
  function openLesson(id){const [,trackId,num]=id.match(/^([a-z]+)-(\d+)$/)||[];const t=tracks.find(x=>x.id===trackId),i=Number(num)-1;if(!t||!t.lessons[i])return;if(user.hearts<=0&&!user.completedNodes.includes(id)){openModal('#heartsModal');return}activeNode={id,track:t,index:i,definition:t.lessons[i]};const l=activeNode.definition;$('#lessonTrackLabel').textContent=t.name.toUpperCase();$('#lessonTitle').textContent=l.title;$('#lessonNumber').textContent=`LESSON ${String(i+1).padStart(2,'0')} · ${String(t.lessons.length).padStart(2,'0')}`;$('#challengeTitle').textContent=l.concept;$('#lessonTheory').textContent=l.theory;$('#challengePrompt').textContent=l.prompt;$('#editorLanguage').textContent=t.short.toUpperCase();$('#codeEditor').value=l.code;syncLines();$('#feedback').hidden=true;$('#feedback').className='feedback';$('#testTitle').textContent='Ready when you are';$('#testDetail').textContent='Run your code to check your work';$('.test-card').className='test-card';$('#testIcon').textContent='◉';$('#previewTip').textContent='Your code runs safely in its own little sandbox.';$('#lessonProgressFill').style.width=`${user.completedNodes.includes(id)?100:Math.max(14,(i+1)/t.lessons.length*100)}%`;updateLives();$('#lessonModal').hidden=false;runPreview(false);}
  function openModal(sel){$(sel).hidden=false;}
  function closeLesson(){$('#lessonModal').hidden=true;activeNode=null;}
  function updateLives(){$('#lessonLives').textContent=Array.from({length:5},(_,i)=>i<user.hearts?'♥':'♡').join(' ');}
  function syncLines(){const n=$('#codeEditor').value.split('\n').length;$('#lineNumbers').textContent=Array.from({length:n},(_,i)=>i+1).join('\n');}
  function runPreview(validate=true){if(!activeNode)return;if(validate){clearTimeout(previewTimer);previewTimer=null;}const frame=$('#previewFrame'),code=$('#codeEditor').value,previewToken=`p${Date.now()}${Math.random().toString(36).slice(2)}`;let finished=false;if(/\b(?:while\s*\(|for\s*\(|setInterval\s*\()/i.test(code)){if(validate)handleResult({ok:false,reason:'This practice sandbox blocks repeating loops and timers. Use the lesson tools to make your change.'});else frame.srcdoc='<p style="font:14px system-ui;padding:18px;color:#68777d">Repeating loops and timers are paused in this practice preview.</p>';return}const listener=(event)=>{if(event.source!==frame.contentWindow||event.data?.type!=='devlingo-report'||event.data?.token!==previewToken||finished)return;finished=true;window.removeEventListener('message',listener);if(!validate)return;const result=window.DEVLINGO_VALIDATE(activeNode.definition,code,event.data.report);handleResult(result);};window.addEventListener('message',listener);
    const track=activeNode.track.id;const jq=track==='jquery'?'<script src="https://code.jquery.com/jquery-3.7.1.min.js"><\/script>':'';
    const reportScript=`<script>(function(){function send(){try{var b=document.body,els=[...b.querySelectorAll('*')],text=b.innerText||b.textContent||'',r={tags:els.map(e=>e.tagName.toLowerCase()),text:text,ids:els.map(e=>e.id).filter(Boolean),classes:els.flatMap(e=>[...e.classList]),error:null};var expected=${JSON.stringify(activeNode.definition.preview.afterClick||null)};if(expected){var target=document.getElementById(expected.id),btn=document.querySelector('button');if(btn){btn.click();setTimeout(function(){r.afterClick=!!(target&&(target.innerText||target.textContent||'').includes(expected.text));parent.postMessage({type:'devlingo-report',token:${JSON.stringify(previewToken)},report:r},'*')},150);return}}parent.postMessage({type:'devlingo-report',token:${JSON.stringify(previewToken)},report:r},'*')}catch(e){parent.postMessage({type:'devlingo-report',token:${JSON.stringify(previewToken)},report:{tags:[],text:'',ids:[],classes:[],error:String(e)}},'*')}}setTimeout(send,${track==='jquery'?1700:450})})();<\/script>`;
    const shellStyle='<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{min-height:100%;}body{display:block;min-height:100vh;font:16px system-ui,sans-serif;color:#263238;background:#fff;padding:18px;margin:0}button{cursor:pointer;padding:8px 13px}img{max-width:100%;height:auto}</style>';
    let html;if(/<html[\s>]/i.test(code)){html=code;if(/<head[\s>]/i.test(html))html=html.replace(/<head([^>]*)>/i,`<head$1>${shellStyle}${jq}`);else html=html.replace(/<html([^>]*)>/i,`<html$1><head>${shellStyle}${jq}</head>`);if(/<\/body>/i.test(html))html=html.replace(/<\/body>/i,`${reportScript}</body>`);else html=html.replace(/<\/html>/i,`${reportScript}</html>`);if(!html.includes(reportScript))html+=reportScript;}else html=`<!doctype html><html><head>${shellStyle}${jq}</head><body>${code}${reportScript}</body></html>`;
    frame.srcdoc=html; if(!validate){window.setTimeout(()=>window.removeEventListener('message',listener),4000);return}$('#testTitle').textContent='Checking your work…';$('#testDetail').textContent='Running your code in the preview';$('.test-card').className='test-card';$('#testIcon').textContent='◌';window.setTimeout(()=>{if(finished)return;finished=true;window.removeEventListener('message',listener);handleResult({ok:false,reason:track==='jquery'?'jQuery is still loading. Check your connection and run again.':'No preview response yet. Check your code and run again.'})},4500);
  }
  function expectedOutput(){const d=activeNode.definition,p=d.preview||{};if(p.afterClick)return `Expected output: click the button and “${p.afterClick.text}” appears on the page.`;if(p.text)return `Expected output: the preview shows “${p.text}”${p.tag?` inside a <${p.tag}>`:''}.`;if(p.tag)return `Expected output: the preview contains a <${p.tag}>${p.id?` with id="${p.id}"`:''}${p.className?` with class="${p.className}"`:''}.`;return `Expected output: ${d.hint}`;}
  function handleResult(result){const card=$('.test-card');if(result.ok){card.className='test-card success';$('#testIcon').textContent='✓';$('#testTitle').textContent='That’s a win!';$('#testDetail').textContent='Your code passed the lesson check.';$('#feedback').hidden=false;$('#feedback').className='feedback success';$('#feedback').textContent='Nice work. You made it happen! +20 XP';sound(true);if(window.confetti)window.confetti({particleCount:90,spread:62,origin:{y:.68},colors:['#58cc02','#1cb0f6','#ffbc18','#ff6b6b']});completeLesson();}else{card.className='test-card error';$('#testIcon').textContent='↺';$('#testTitle').textContent='Not quite yet — take another look';$('#testDetail').textContent='Compare the preview with the expected output, then retry.';$('#feedback').hidden=false;$('#feedback').className='feedback error';$('#feedback').textContent=`${result.reason||activeNode.definition.hint} ${expectedOutput()} Make the change and press Run code to retry.`;sound(false);user.hearts=Math.max(0,user.hearts-1);persist();updateLives();document.querySelector('.lesson-modal').classList.remove('shake');void document.querySelector('.lesson-modal').offsetWidth;document.querySelector('.lesson-modal').classList.add('shake');if(user.hearts===0)setTimeout(()=>{$('#lessonModal').hidden=true;openModal('#heartsModal')},700);}}
  function completeLesson(){const id=activeNode.id,wasDone=user.completedNodes.includes(id);let earned=null;if(!wasDone){user.completedNodes.push(id);user.xp+=20;user.level=Math.max(user.level+1,user.startLevel+user.completedNodes.length);user.hearts=Math.min(5,user.hearts+1);const track=activeNode.track;if(track.lessons.every((_,i)=>user.completedNodes.includes(`${track.id}-${i+1}`))&&!user.badges.includes(track.id)){user.badges.push(track.id);earned=track.id;}updateStreak();persist();render();$('#lessonProgressFill').style.width='100%';toast(earned?'Track complete! Badge earned!':'Lesson complete! +20 XP');}else{user.hearts=Math.min(5,user.hearts+1);persist();toast('Review complete. +1 heart');}updateLives();activeNode.reviewing=false;if(earned){const [title,message]=BADGES[earned];$('#badgeTitle').textContent=title;$('#badgeMessage').textContent=message;setTimeout(()=>openModal('#badgeModal'),450);}}
  function hint(){const box=$('#feedback');box.hidden=false;box.className='feedback';box.textContent=activeNode.definition.hint;$('#previewTip').textContent='Try the hint, then run your code again.';}
  function restoreHearts(){const done=user.completedNodes.find(id=>{const [,t,n]=id.match(/^([a-z]+)-(\d+)$/)||[];return t&&tracks.find(x=>x.id===t)?.lessons[Number(n)-1]});if(done){$('#heartsModal').hidden=true;activeTrack=done.split('-')[0];render();openLesson(done);activeNode.reviewing=true;toast('Review a lesson to earn a heart back.');}else{user.hearts=1;persist();render();$('#heartsModal').hidden=true;toast('Your first lesson is waiting. Give it a go!');}}
  document.addEventListener('click',e=>{const track=e.target.closest('[data-track]');if(track){activeTrack=track.dataset.track;render();return}const node=e.target.closest('[data-node]');if(node&&!node.disabled){openLesson(node.dataset.node);return}if(e.target.closest('.close-lesson'))closeLesson();});
  $$('.tier-card').forEach(c=>c.addEventListener('click',()=>{$$('.tier-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');selectedTier=c.dataset.tier;}));$('#startLearning').addEventListener('click',startUser);$('#runCode').addEventListener('click',()=>runPreview(true));$('#hintButton').addEventListener('click',hint);$('#codeEditor').addEventListener('input',()=>{syncLines();clearTimeout(previewTimer);previewTimer=setTimeout(()=>runPreview(false),320)});$('#codeEditor').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const a=e.target,s=a.selectionStart;a.value=a.value.slice(0,s)+'  '+a.value.slice(a.selectionEnd);a.selectionStart=a.selectionEnd=s+2;syncLines();clearTimeout(previewTimer);previewTimer=setTimeout(()=>runPreview(false),320);}});$('#themeToggle').addEventListener('click',()=>{user.theme=user.theme==='dark'?'light':'dark';persist();applyTheme();});$('#profileButton').addEventListener('click',()=>{const name=window.prompt('What should we call you?',user.name||'');if(name!==null){user.name=name.trim().slice(0,24);persist();render();}});$('#closeBadge').addEventListener('click',()=>$('#badgeModal').hidden=true);$('#closeHearts').addEventListener('click',()=>$('#heartsModal').hidden=true);$('#reviewLesson').addEventListener('click',restoreHearts);$('#resetProgress').addEventListener('click',()=>{if(window.confirm('Start fresh? This clears your saved name, level, XP, streak, hearts, and lesson progress from this browser.')){localStorage.removeItem(KEY);window.location.reload();}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#lessonModal').hidden)closeLesson();if(!$('#heartsModal').hidden)$('#heartsModal').hidden=true;if(!$('#badgeModal').hidden)$('#badgeModal').hidden=true;}});
  init();
})();
