/* All lesson copy, starter code and checks live here. Checks use both the submitted
   source and a small DOM snapshot reported by the isolated preview iframe. */
(() => {
  const lesson = (title, concept, theory, prompt, code, hint, checks, preview = {}) => ({ title, concept, theory, prompt, code, hint, checks, preview });
  window.DEVLINGO_TRACKS = [
    { id:'html', name:'HTML Foundations', short:'HTML', icon:'⌘', color:'blue', lessons:[
      lesson('The Skeleton','Your first page','Every webpage has a little behind-the-scenes structure. The doctype tells the browser what rules to use; head keeps page info; body holds everything people actually see.','Give this page its basic HTML skeleton. Make sure the heading lives inside the body.','<!doctype html>\n<html>\n  <head>\n    <title>My first page</title>\n  </head>\n  <body>\n    <h1>Hello, world!</h1>\n  </body>\n</html>','Your page needs a doctype, an html element, a head, and a body. Put the heading inside the body.',[/<!doctype\s+html/i,/<html[\s>]/i,/<head[\s>]/i,/<body[\s>]/i,/<h1[\s>]/i],{tag:'h1',text:'Hello, world!'}),
      lesson('Text & Semantics','Give your words meaning','Headings give a page its outline. Paragraphs hold regular copy, while strong and mark add meaning and emphasis. Choose elements for what words mean, not just how they look.','Add a page heading, a paragraph, bold importance, and a highlighted word.','<h1>My tiny wins</h1>\n<p>I am learning to <strong>build</strong> for the web.</p>\n<p><mark>One step at a time</mark> is still progress.</p>','Use an h1, a p, strong, and mark. Put the highlighted words inside the mark element.',[/<h1[\s>]/i,/<p[\s>]/i,/<strong[\s>]/i,/<mark[\s>]/i],{tag:'h1',text:'My tiny wins'}),
      lesson('Elements & Media','Link it up','Links use href to point somewhere. Images use src for the image and alt text so everyone knows what it shows—even if it cannot load.','Add a link with an href and an image with src and helpful alt text.','<a href="https://example.com">Visit my favorite place</a>\n<img src="https://placehold.co/240x120" alt="A colorful placeholder">','Add an <a> with href and an <img> with both src and alt.',[/<a\b[^>]*\bhref\s*=/i,/<img\b[^>]*\bsrc\s*=/i,/<img\b[^>]*\balt\s*=/i],{tag:'a',text:'Visit my favorite place'}),
      lesson('User Inputs','Let people join in','Forms collect information from people. Inputs are for typing, labels make fields clearer, and buttons give people something to do.','Create a text input and a button inside a form.','<form>\n  <label for="name">Your name</label>\n  <input id="name" type="text" placeholder="Type here">\n  <button type="button">Say hi</button>\n</form>','Add a form, an input with type="text", and a button.',[/<form[\s>]/i,/<input\b[^>]*type\s*=\s*["']?text/i,/<button[\s>]/i],{tag:'button',text:'Say hi'})
    ]},
    { id:'css', name:'Modern CSS', short:'CSS', icon:'✳', color:'purple', lessons:[
      lesson('Selectors & Colors','Style with intention','CSS selectors pick the things you want to style. A dot selects a class, a hash selects an id. Then properties like color and background-color bring the page to life.','Make the button green using its .btn class. Give the hero a background color.','<style>\n  .btn { color: #16833a; background-color: #d9f7df; }\n  #hero { background-color: #eef9ff; }\n</style>\n<section id="hero"><button class="btn">Make it pop</button></section>','Add a .btn selector with a color and a #hero selector with a background-color.',[/\.btn\s*\{[^}]*color\s*:/i,/#hero\s*\{[^}]*background(?:-color)?\s*:/i],{tag:'button',text:'Make it pop',className:'btn'}),
      lesson('The Box Model','Give it some space','Each element is a box: content, padding, border, then margin. Padding is breathing room inside; margin is space outside. border-box makes sizing way less surprising.','Add padding, a border, margin, and box-sizing to the card.','<style>\n  .card { box-sizing: border-box; padding: 24px; border: 2px solid #263238; margin: 16px; }\n</style>\n<div class="card">A little breathing room</div>','Give .card padding, border, margin, and box-sizing: border-box.',[/padding\s*:/i,/border\s*:/i,/margin\s*:/i,/box-sizing\s*:\s*border-box/i],{tag:'div',text:'A little breathing room',className:'card'}),
      lesson('Flexbox Arena','Make room for everyone','Flexbox lines children up without a pile of tricky positioning. Set display to flex, then choose how items sit across and down the container.','Center these cards in a row with Flexbox.','<style>\n  .row { display: flex; justify-content: center; align-items: center; gap: 12px; }\n  .card { padding: 18px; background: #e7f7df; }\n</style>\n<div class="row"><div class="card">One</div><div class="card">Two</div></div>','Set .row to display:flex and use justify-content and align-items.',[/display\s*:\s*flex/i,/justify-content\s*:/i,/align-items\s*:/i],{tag:'div',text:'One',className:'card'}),
      lesson('Modern Polish','Make it feel right','A soft corner or a tiny transition can make an interface feel thoughtful. Hover styles respond to people, and transition helps changes feel smooth instead of jumpy.','Give the button rounded corners, a transition, and a hover state.','<style>\n  .btn { border-radius: 12px; transition: transform .2s, background .2s; }\n  .btn:hover { transform: translateY(-2px); background: #58cc02; }\n</style>\n<button class="btn">Hover over me</button>','Add border-radius and transition to .btn, plus a .btn:hover rule.',[/border-radius\s*:/i,/transition\s*:/i,/\.btn\s*:\s*hover/i],{tag:'button',text:'Hover over me',className:'btn'})
    ]},
    { id:'js', name:'Vanilla JavaScript', short:'JavaScript', icon:'⚡', color:'yellow', lessons:[
      lesson('Variables & Types','Save a little info','Use const when a value should stay put and let when it should change. Template literals use backticks so you can slip values right into a string.','Create a greeting using const and a template literal.','const name = "friend";\nconst greeting = `Hey, ${name}!`;\ndocument.body.innerHTML = `<h1>${greeting}</h1>`;','Declare a const and use backticks with ${name} to build the greeting.',[/\bconst\s+\w+/i,/`[^`]*\$\{/],{tag:'h1',text:'Hey, friend!'}),
      lesson('DOM Query & Mutation','Find it. Change it.','The DOM is the browser’s live map of a page. querySelector finds the first match. Then textContent or style lets you update what people see.','Select the message and change its text and color.','<p id="message">Not quite yet…</p>\n<script>\nconst message = document.querySelector("#message");\nmessage.textContent = "You found me!";\nmessage.style.color = "green";\n</script>','Use document.querySelector, then update textContent and style.',[/document\.querySelector\s*\(/i,/\.textContent\s*=/i,/\.style\./i],{tag:'p',text:'You found me!',id:'message'}),
      lesson('Event Listeners','Make it respond','An event listener waits for something to happen. Add a click listener to your button and the callback runs when someone taps it.','Make the button update the message when clicked.','<button id="btn">Tap me</button>\n<p id="message">Waiting…</p>\n<script>\ndocument.querySelector("#btn").addEventListener("click", () => {\n  document.querySelector("#message").textContent = "It worked!";\n});\n</script>','Add addEventListener("click", ...) and change the message text in the callback.',[/addEventListener\s*\(\s*["']click/i,/\.textContent\s*=/i],{tag:'button',text:'Tap me',id:'btn',afterClick:{id:'message',text:'It worked!'}}),
      lesson('State & Logic','A little logic goes far','An if/else lets code choose what to do. Arrays hold lists; forEach visits every item. Combine them to update a whole set of things at once.','Use a condition and forEach to label every skill.','<ul id="skills"><li>HTML</li><li>CSS</li><li>JavaScript</li></ul>\n<script>\nconst skills = document.querySelectorAll("#skills li");\nif (skills.length > 0) {\n  skills.forEach((skill) => { skill.textContent += " ✓"; });\n}\n</script>','Use if/else (or if) and .forEach() to update each skill.',[/\bif\s*\(/i,/\.forEach\s*\(/i],{tag:'li',text:'HTML ✓'})
    ]},
    { id:'jquery', name:'jQuery Speedrun', short:'jQuery', icon:'⌁', color:'pink', lessons:[
      lesson('The jQuery Selector','Less typing, same power','jQuery wraps matching elements in a handy collection. The $() selector feels familiar if you know CSS: use # for an id, dot for a class.','Select the button with jQuery and change its text.','<button id="btn">Old label</button>\n<script>\n$("#btn").text("jQuery found me!");\n</script>','Use $("#btn") and call .text() with a new label.',[/\$\s*\(\s*["']#btn["']\s*\)/,/\.text\s*\(/i],{tag:'button',text:'jQuery found me!',id:'btn'}),
      lesson('Event Handling','Listen with jQuery','The .on() method attaches an event handler to a selection. It keeps your click behavior close to the element it belongs to.','Use jQuery .on() to change the message after a click.','<button id="btn">Tap me</button>\n<p id="message">Waiting…</p>\n<script>\n$("#btn").on("click", function() {\n  $("#message").text("Nice click!");\n});\n</script>','Use $("#btn").on("click", function(){ ... }) and update #message.',[/\$\s*\(\s*["']#btn["']\s*\)\.on\s*\(\s*["']click/i,/\.text\s*\(/i],{tag:'button',text:'Tap me',id:'btn',afterClick:{id:'message',text:'Nice click!'}}),
      lesson('DOM Effects & Animations','A little motion','jQuery effects are shortcuts for common animations. fadeIn shows something gently, slideToggle expands or collapses it, and css updates a style.','Use jQuery to set a color and toggle the panel.','<button id="btn">Toggle the note</button>\n<div id="panel" style="display:none">Surprise! ✨</div>\n<script>\n$("#btn").css("color", "green").on("click", function() {\n  $("#panel").slideToggle();\n});\n</script>','Chain .css() and .on(), then call .slideToggle() on #panel.',[/\.css\s*\(/i,/\.slideToggle\s*\(/i,/\.on\s*\(/i],{tag:'button',text:'Toggle the note',id:'btn'}),
      lesson('Chaining & Dynamic HTML','Build as you go','jQuery methods return the collection, so you can chain changes together. Add a class, append new HTML, and keep the whole transformation readable.','Add the active class and append a “Done” note to the card.','<div class="card">My card</div>\n<script>\n$(".card").addClass("active").append("<p>Done</p>");\n</script>','Chain .addClass("active") and .append("<p>Done</p>") on .card.',[/\.addClass\s*\(\s*["']active["']/i,/\.append\s*\(\s*["']<p>Done<\/p>["']/i],{tag:'div',text:'My card',className:'card',addedClass:'active',addedText:'Done'})
    ]}
  ];
  window.DEVLINGO_VALIDATE = function(def, code, report) {
    const source=def.checks.every(rx=>rx.test(code));
    if (!source) return {ok:false,reason:'Check the code for the key pieces in the hint.'};
    if (report && report.error) return {ok:false,reason:'There is a code error in the preview. Check your brackets and quotes.'};
    const p=def.preview||{};
    if(p.tag && report && !report.tags.includes(p.tag)) return {ok:false,reason:`Add a <${p.tag}> element to your page.`};
    if(p.text && report && !(report.text||'').includes(p.text)) return {ok:false,reason:`Make sure “${p.text}” appears in your preview.`};
    if(p.id && report && !report.ids.includes(p.id)) return {ok:false,reason:`Make sure the element has id="${p.id}".`};
    if(p.className && report && !report.classes.includes(p.className)) return {ok:false,reason:`Add the .${p.className} class to the right element.`};
    if(p.afterClick && report && !report.afterClick) return {ok:false,reason:'The click did not update the message yet. Check your event handler.'};
    if(p.addedClass && report && !report.classes.includes(p.addedClass)) return {ok:false,reason:'Make sure the card gets the active class.'};
    if(p.addedText && report && !(report.text||'').includes(p.addedText)) return {ok:false,reason:'Append the new paragraph to your card.'};
    return {ok:true};
  };
})();
