/* All lesson copy, starter code and checks live here. Checks use both the submitted
   source and a small DOM snapshot reported by the isolated preview iframe. */
(() => {
  const lesson = (title, concept, theory, prompt, code, hint, checks, preview = {}) => ({ title, concept, theory, prompt, code, hint, checks, preview });
  window.DEVLINGO_TRACKS = [
    { id:'html', name:'HTML Foundations', short:'HTML', icon:'⌘', color:'blue', lessons:[
      lesson('The Skeleton','Your first page','Every webpage has a little behind-the-scenes structure. The doctype tells the browser what rules to use; head keeps page info; body holds everything people actually see.','Give this page its basic HTML skeleton. Make sure the heading lives inside the body.','<!doctype html>\n<html>\n  <head>\n    <title>My first page</title>\n  </head>\n  <body>\n    <h1>Hello, world!</h1>\n  </body>\n</html>','Your page needs a doctype, an html element, a head, and a body. Put the heading inside the body.',[/<!doctype\s+html/i,/<html[\s>]/i,/<head[\s>]/i,/<body[\s>]/i,/<h1[\s>]/i],{tag:'h1',text:'Hello, world!'}),
      lesson('Text & Semantics','Give your words meaning','Headings give a page its outline. Paragraphs hold regular copy, while strong and mark add meaning and emphasis. Choose elements for what words mean, not just how they look.','Add a page heading, a paragraph, bold importance, and a highlighted word.','<h1>My tiny wins</h1>\n<p>I am learning to <strong>build</strong> for the web.</p>\n<p><mark>One step at a time</mark> is still progress.</p>','Use an h1, a p, strong, and mark. Put the highlighted words inside the mark element.',[/<h1[\s>]/i,/<p[\s>]/i,/<strong[\s>]/i,/<mark[\s>]/i],{tag:'h1',text:'My tiny wins'}),
      lesson('Elements & Media','Link it up','Links use href to point somewhere. Images use src for the image and alt text so everyone knows what it shows—even if it cannot load.','Add a link with an href and an image with src and helpful alt text.','<a href="https://example.com">Visit my favorite place</a>\n<img src="https://placehold.co/240x120" alt="A colorful placeholder">','Add an <a> with href and an <img> with both src and alt.',[/<a\b[^>]*\bhref\s*=/i,/<img\b[^>]*\bsrc\s*=/i,/<img\b[^>]*\balt\s*=/i],{tag:'a',text:'Visit my favorite place'}),
      lesson('User Inputs','Let people join in','Forms collect information from people. Inputs are for typing, labels make fields clearer, and buttons give people something to do.','Create a text input and a button inside a form.','<form>\n  <label for="name">Your name</label>\n  <input id="name" type="text" placeholder="Type here">\n  <button type="button">Say hi</button>\n</form>','Add a form, an input with type="text", and a button.',[/<form[\s>]/i,/<input\b[^>]*type\s*=\s*["']?text/i,/<button[\s>]/i],{tag:'button',text:'Say hi'}),
      lesson('Page Landmarks','Map the page','Landmarks give a page a useful outline. A header introduces the site, nav groups links, main holds the unique content, and footer closes things out. These are the first clues when checking a vibe-coded page.','Give this page header, nav, main, and footer landmarks.','<header><h1>Studio Day</h1></header>\n<nav><a href="#work">Work</a></nav>\n<main id="work"><h2>Recent work</h2><p>Three things in progress.</p></main>\n<footer>Made with care</footer>','Use header, nav, main, and footer elements. Keep the main content inside main.',[/<header[\s>]/i,/<nav[\s>]/i,/<main[\s>]/i,/<footer[\s>]/i],{tag:'main',text:'Recent work'}),
      lesson('Nesting & Lists','Check the structure','HTML elements can sit inside other elements. Indentation makes that structure easier to read. Lists are useful for checking repeated content in a generated page.','Build a section with a heading and a three-item unordered list.','<section>\n  <h2>Launch checklist</h2>\n  <ul>\n    <li>Check the copy</li>\n    <li>Test the links</li>\n    <li>Review on mobile</li>\n  </ul>\n</section>','Nest a heading and a ul inside section, then add three li elements.',[/<section[\s>]/i,/<h2[\s>]/i,/<ul[\s>]/i,/<li[\s>]/i],{tag:'li',text:'Review on mobile'}),
      lesson('Accessible Labels','Make controls clear','A label connected with for and id gives an input a readable name. Useful alt text describes an image when it cannot be seen. These details help people and make generated interfaces easier to inspect.','Connect a label to an email input and describe the image with alt text.','<label for="email">Email address</label>\n<input id="email" type="email">\n<img src="https://placehold.co/120x80" alt="Blue notebook on a desk">','Match label for to the input id, and add meaningful alt text to the image.',[/<label\b[^>]*for\s*=\s*["']email/i,/<input\b[^>]*id\s*=\s*["']email/i,/<img\b[^>]*alt\s*=/i],{tag:'input',id:'email'}),
      lesson('Links or Buttons?','Choose the right action','Links take people somewhere; buttons do something here. When reviewing generated UI, check that each control matches its job and has a clear name.','Add a link to the guide and a button that updates the status.','<a href="#guide">Read the guide</a>\n<button id="check">Check status</button>\n<p id="status">Not checked yet</p>\n<script>document.querySelector("#check").addEventListener("click", () => { document.querySelector("#status").textContent = "All set"; });</script>','Use an anchor with href and a button that updates #status after click.',[/<a\b[^>]*href\s*=/i,/<button[\s>]/i,/addEventListener\s*\(\s*["']click/i],{tag:'a',text:'Read the guide',afterClick:{id:'status',text:'All set'}})
    ]},
    { id:'css', name:'Modern CSS', short:'CSS', icon:'✳', color:'purple', lessons:[
      lesson('Selectors & Colors','Style with intention','CSS selectors pick the things you want to style. A dot selects a class, a hash selects an id. Then properties like color and background-color bring the page to life.','Make the button green using its .btn class. Give the hero a background color.','<style>\n  .btn { color: #16833a; background-color: #d9f7df; }\n  #hero { background-color: #eef9ff; }\n</style>\n<section id="hero"><button class="btn">Make it pop</button></section>','Add a .btn selector with a color and a #hero selector with a background-color.',[/\.btn\s*\{[^}]*color\s*:/i,/#hero\s*\{[^}]*background(?:-color)?\s*:/i],{tag:'button',text:'Make it pop',className:'btn'}),
      lesson('The Box Model','Give it some space','Each element is a box: content, padding, border, then margin. Padding is breathing room inside; margin is space outside. border-box makes sizing way less surprising.','Add padding, a border, margin, and box-sizing to the card.','<style>\n  .card { box-sizing: border-box; padding: 24px; border: 2px solid #263238; margin: 16px; }\n</style>\n<div class="card">A little breathing room</div>','Give .card padding, border, margin, and box-sizing: border-box.',[/padding\s*:/i,/border\s*:/i,/margin\s*:/i,/box-sizing\s*:\s*border-box/i],{tag:'div',text:'A little breathing room',className:'card'}),
      lesson('Flexbox Arena','Make room for everyone','Flexbox lines children up without a pile of tricky positioning. Set display to flex, then choose how items sit across and down the container.','Center these cards in a row with Flexbox.','<style>\n  .row { display: flex; justify-content: center; align-items: center; gap: 12px; }\n  .card { padding: 18px; background: #e7f7df; }\n</style>\n<div class="row"><div class="card">One</div><div class="card">Two</div></div>','Set .row to display:flex and use justify-content and align-items.',[/display\s*:\s*flex/i,/justify-content\s*:/i,/align-items\s*:/i],{tag:'div',text:'One',className:'card'}),
      lesson('Modern Polish','Make it feel right','A soft corner or a tiny transition can make an interface feel thoughtful. Hover styles respond to people, and transition helps changes feel smooth instead of jumpy.','Give the button rounded corners, a transition, and a hover state.','<style>\n  .btn { border-radius: 12px; transition: transform .2s, background .2s; }\n  .btn:hover { transform: translateY(-2px); background: #58cc02; }\n</style>\n<button class="btn">Hover over me</button>','Add border-radius and transition to .btn, plus a .btn:hover rule.',[/border-radius\s*:/i,/transition\s*:/i,/\.btn\s*:\s*hover/i],{tag:'button',text:'Hover over me',className:'btn'}),
      lesson('The Cascade','Read the winning rule','When styles disagree, specificity and source order decide which value wins. An id selector beats a class selector. This is a practical debugging skill: inspect the selector, then find the rule that actually applies.','Use the #notice rule so the notice text is blue.','<style>\n.notice { color: tomato; }\n#notice { color: #1683c7; }\n</style>\n<p class="notice" id="notice">Inspect this notice</p>','Add a #notice selector with a color declaration.',[/#notice\s*\{[^}]*color\s*:/i],{tag:'p',text:'Inspect this notice',id:'notice'}),
      lesson('Type & Readability','Set a comfy reading rhythm','Readable text uses a sensible size, enough line-height, and a line length that does not stretch across the whole screen. These small CSS choices are easy to verify in any generated page.','Style the article with readable type and a comfortable width.','<style>\n.article { font-size: 1.1rem; line-height: 1.7; max-width: 42rem; }\n</style>\n<article class="article"><h2>A little breathing room</h2><p>Comfortable type helps readers stay with the idea.</p></article>','Give .article font-size, line-height, and max-width.',[/font-size\s*:/i,/line-height\s*:/i,/max-width\s*:/i],{tag:'article',text:'Comfortable type',className:'article'}),
      lesson('Responsive Layout','Make it fit the screen','A media query lets a layout respond to available space. Flexbox can show cards in a row on wide screens and stack them when the viewport gets narrow.','Lay out the cards with flex, then stack them below 600px.','<style>\n.cards { display: flex; gap: 12px; }\n.card { flex: 1; padding: 18px; background: #eaf8ff; }\n@media (max-width: 600px) { .cards { flex-direction: column; } }\n</style>\n<div class="cards"><article class="card">Plan</article><article class="card">Build</article></div>','Use display:flex and a max-width media query that sets flex-direction: column.',[/display\s*:\s*flex/i,/@media\s*\(\s*max-width\s*:/i,/flex-direction\s*:\s*column/i],{tag:'article',text:'Plan',className:'card'}),
      lesson('Focus & States','Design for every input','People navigate with a mouse, keyboard, touch, and assistive technology. A visible focus style helps keyboard users see where they are. Hover is a bonus state, never the only clue.','Add a hover style and a visible keyboard focus outline.','<style>\n.btn { border: 2px solid #263238; border-radius: 10px; padding: 10px 16px; }\n.btn:hover { background: #e8f8df; }\n.btn:focus-visible { outline: 3px solid #1cb0f6; outline-offset: 3px; }\n</style>\n<button class="btn">Try keyboard focus</button>','Style .btn:hover and .btn:focus-visible with a clear outline.',[/\.btn\s*:\s*hover/i,/\.btn\s*:\s*focus-visible/i,/outline\s*:/i],{tag:'button',text:'Try keyboard focus',className:'btn'})
    ]},
    { id:'js', name:'Vanilla JavaScript', short:'JavaScript', icon:'⚡', color:'yellow', lessons:[
      lesson('Variables & Types','Save a little info','Use const when a value should stay put and let when it should change. Template literals use backticks so you can slip values right into a string.','Create a greeting using const and a template literal.','const name = "friend";\nconst greeting = `Hey, ${name}!`;\ndocument.body.innerHTML = `<h1>${greeting}</h1>`;','Declare a const and use backticks with ${name} to build the greeting.',[/\bconst\s+\w+/i,/`[^`]*\$\{/],{tag:'h1',text:'Hey, friend!'}),
      lesson('DOM Query & Mutation','Find it. Change it.','The DOM is the browser’s live map of a page. querySelector finds the first match. Then textContent or style lets you update what people see.','Select the message and change its text and color.','<p id="message">Not quite yet…</p>\n<script>\nconst message = document.querySelector("#message");\nmessage.textContent = "You found me!";\nmessage.style.color = "green";\n</script>','Use document.querySelector, then update textContent and style.',[/document\.querySelector\s*\(/i,/\.textContent\s*=/i,/\.style\./i],{tag:'p',text:'You found me!',id:'message'}),
      lesson('Event Listeners','Make it respond','An event listener waits for something to happen. Add a click listener to your button and the callback runs when someone taps it.','Make the button update the message when clicked.','<button id="btn">Tap me</button>\n<p id="message">Waiting…</p>\n<script>\ndocument.querySelector("#btn").addEventListener("click", () => {\n  document.querySelector("#message").textContent = "It worked!";\n});\n</script>','Add addEventListener("click", ...) and change the message text in the callback.',[/addEventListener\s*\(\s*["']click/i,/\.textContent\s*=/i],{tag:'button',text:'Tap me',id:'btn',afterClick:{id:'message',text:'It worked!'}}),
      lesson('State & Logic','A little logic goes far','An if/else lets code choose what to do. Arrays hold lists; forEach visits every item. Combine them to update a whole set of things at once.','Use a condition and forEach to label every skill.','<ul id="skills"><li>HTML</li><li>CSS</li><li>JavaScript</li></ul>\n<script>\nconst skills = document.querySelectorAll("#skills li");\nif (skills.length > 0) {\n  skills.forEach((skill) => { skill.textContent += " ✓"; });\n}\n</script>','Use if/else (or if) and .forEach() to update each skill.',[/\bif\s*\(/i,/\.forEach\s*\(/i],{tag:'li',text:'HTML ✓'})
    ]},
    { id:'jquery', name:'jQuery Speedrun', short:'jQuery', icon:'⌁', color:'pink', lessons:[
      lesson('The jQuery Selector','Less typing, same power','jQuery wraps matching elements in a handy collection. The $() selector feels familiar if you know CSS: use # for an id, dot for a class.','Select the button with jQuery and change its text.','<button id="btn">Old label</button>\n<script>\n$("#btn").text("jQuery found me!");\n</script>','Use $("#btn") and call .text() with a new label.',[/\$\s*\(\s*["']#btn["']\s*\)/,/\.text\s*\(/i],{tag:'button',text:'jQuery found me!',id:'btn'}),
      lesson('Event Handling','Listen with jQuery','The .on() method attaches an event handler to a selection. It keeps your click behavior close to the element it belongs to.','Use jQuery .on() to change the message after a click.','<button id="btn">Tap me</button>\n<p id="message">Waiting…</p>\n<script>\n$("#btn").on("click", function() {\n  $("#message").text("Nice click!");\n});\n</script>','Use $("#btn").on("click", function(){ ... }) and update #message.',[/\$\s*\(\s*["']#btn["']\s*\)\.on\s*\(\s*["']click/i,/\.text\s*\(/i],{tag:'button',text:'Tap me',id:'btn',afterClick:{id:'message',text:'Nice click!'}}),
      lesson('DOM Effects & Animations','A little motion','jQuery effects are shortcuts for common animations. fadeIn shows something gently, slideToggle expands or collapses it, and css updates a style.','Use jQuery to set a color and toggle the panel.','<button id="btn">Toggle the note</button>\n<div id="panel" style="display:none">Surprise! ✨</div>\n<script>\n$("#btn").css("color", "green").on("click", function() {\n  $("#panel").slideToggle();\n});\n</script>','Chain .css() and .on(), then call .slideToggle() on #panel.',[/\.css\s*\(/i,/\.slideToggle\s*\(/i,/\.on\s*\(/i],{tag:'button',text:'Toggle the note',id:'btn'}),
      lesson('Chaining & Dynamic HTML','Build as you go','jQuery methods return the collection, so you can chain changes together. Add a class, append new HTML, and keep the whole transformation readable.','Add the active class and append a “Done” note to the card.','<div class="card">My card</div>\n<script>\n$(".card").addClass("active").append("<p>Done</p>");\n</script>','Chain .addClass("active") and .append("<p>Done</p>") on .card.',[/\.addClass\s*\(\s*["']active["']/i,/\.append\s*\(\s*["']<p>Done<\/p>["']/i],{tag:'div',text:'My card',className:'card',addedClass:'active',addedText:'Done'})
    ]}
  ];
  window.DEVLINGO_VALIDATE = function(def, code, report) {
    const source=def.checks.every(rx=>rx.test(code));
    if (!source) return {ok:false,reason:'Check the code for the key pieces in the hint.'};
    if (report && report.error) return {ok:false,reason:'There is a code error in the preview. Check your brackets and quotes.'};
    const p=def.preview||{};
    if(p.tag && report && !report.tags.includes(p.tag)) return {ok:false,reason:`Add a <${p.tag}> element to your page.`};
    if(p.text && report && !(report.text||'').includes(p.text)) return {ok:false,reason:`Make sure “${p.text}” appears in your preview.`};
    if(p.id && report && !report.ids.includes(p.id)) return {ok:false,reason:`Make sure the element has id="${p.id}".`};
    if(p.className && report && !report.classes.includes(p.className)) return {ok:false,reason:`Add the .${p.className} class to the right element.`};
    if(p.afterClick && report && !report.afterClick) return {ok:false,reason:'The click did not update the message yet. Check your event handler.'};
    if(p.addedClass && report && !report.classes.includes(p.addedClass)) return {ok:false,reason:'Make sure the card gets the active class.'};
    if(p.addedText && report && !(report.text||'').includes(p.addedText)) return {ok:false,reason:'Append the new paragraph to your card.'};
    return {ok:true};
  };
})();
